DECLARE
  column_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO column_count
  FROM user_tab_columns
  WHERE table_name = 'DIPLOMA'
    AND column_name = 'DOCUMENT_FILE_NAME';

  IF column_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE DIPLOMA ADD (
        DOCUMENT_FILE_NAME VARCHAR2(255),
        DOCUMENT_MIME_TYPE VARCHAR2(100),
        DOCUMENT_FILE_SIZE NUMBER,
        DOCUMENT_FILE_CONTENT BLOB,
        DOCUMENT_UPLOADED_AT DATE DEFAULT SYSDATE
      )
    ]';
  END IF;
END;
/

DECLARE
  column_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO column_count
  FROM user_tab_columns
  WHERE table_name = 'UVERENJEOPOLOZENIMPREDMETIMA'
    AND column_name = 'DOCUMENT_FILE_NAME';

  IF column_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE UVERENJEOPOLOZENIMPREDMETIMA ADD (
        DOCUMENT_FILE_NAME VARCHAR2(255),
        DOCUMENT_MIME_TYPE VARCHAR2(100),
        DOCUMENT_FILE_SIZE NUMBER,
        DOCUMENT_FILE_CONTENT BLOB,
        DOCUMENT_UPLOADED_AT DATE DEFAULT SYSDATE,
        UKUPNO_ESPB NUMBER(5,2),
        PROSECNA_OCENA NUMBER(4,2)
      )
    ]';
  END IF;
END;
/

COMMENT ON COLUMN DIPLOMA.DOCUMENT_FILE_NAME IS 'Originalni naziv otpremljene diplome';
COMMENT ON COLUMN DIPLOMA.DOCUMENT_MIME_TYPE IS 'MIME tip otpremljene diplome';
COMMENT ON COLUMN DIPLOMA.DOCUMENT_FILE_SIZE IS 'Velicina fajla diplome u bajtovima';
COMMENT ON COLUMN DIPLOMA.DOCUMENT_FILE_CONTENT IS 'BLOB sadrzaj otpremljene diplome';
COMMENT ON COLUMN DIPLOMA.DOCUMENT_UPLOADED_AT IS 'Datum i vreme otpremanja diplome';

COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.DOCUMENT_FILE_NAME IS 'Originalni naziv otpremljenog uverenja';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.DOCUMENT_MIME_TYPE IS 'MIME tip otpremljenog uverenja';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.DOCUMENT_FILE_SIZE IS 'Velicina fajla uverenja u bajtovima';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.DOCUMENT_FILE_CONTENT IS 'BLOB sadrzaj otpremljenog uverenja';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.DOCUMENT_UPLOADED_AT IS 'Datum i vreme otpremanja uverenja';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.UKUPNO_ESPB IS 'Ukupan broj ESPB bodova iz uverenja';
COMMENT ON COLUMN UVERENJEOPOLOZENIMPREDMETIMA.PROSECNA_OCENA IS 'Prosecna ocena sa osnovnih studija';
