DECLARE
  constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO constraint_count
  FROM user_constraints
  WHERE table_name = 'UPIS_FINALIZACIJA'
    AND constraint_name = 'CK_UPIS_FINALIZACIJA_STATUS';

  IF constraint_count > 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE UPIS_FINALIZACIJA
      DROP CONSTRAINT CK_UPIS_FINALIZACIJA_STATUS
    ]';
  END IF;
END;
/

UPDATE STAVKARANGLISTE
SET STATUS = 'BodoviUneti'
WHERE STATUS = 'Scored';

UPDATE STAVKARANGLISTE
SET STATUS = 'Odobrena'
WHERE STATUS = 'Approved';

UPDATE UPIS_FINALIZACIJA
SET STATUS_UPISA = 'UgovorOtpremljen'
WHERE STATUS_UPISA = 'ContractSubmitted';

UPDATE UPIS_FINALIZACIJA
SET STATUS_UPISA = 'UpisZavrsen'
WHERE STATUS_UPISA = 'EnrollmentCompleted';

ALTER TABLE UPIS_FINALIZACIJA
ADD CONSTRAINT CK_UPIS_FINALIZACIJA_STATUS
CHECK (STATUS_UPISA IN ('UgovorOtpremljen', 'UpisZavrsen'));

COMMENT ON COLUMN UPIS_FINALIZACIJA.STATUS_UPISA IS 'UgovorOtpremljen ili UpisZavrsen';

COMMIT;
