DECLARE
  column_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO column_count
  FROM user_tab_columns
  WHERE table_name = 'KONACNARANGLISTA'
    AND column_name = 'ID_KONKURSA';

  IF column_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE KONACNARANGLISTA ADD (ID_KONKURSA NUMBER)
    ]';
  END IF;
END;
/

UPDATE KONACNARANGLISTA kr
SET kr.ID_KONKURSA = (
  SELECT MIN(p.ID_KONKURSA)
  FROM STAVKARANGLISTE s
  JOIN PRIJAVA p ON p.BROJ_PRIJAVE = s.BROJ_PRIJAVE
  WHERE s.ID_RANG_LISTE = kr.ID_RANG_LISTE
    AND p.ID_KONKURSA IS NOT NULL
)
WHERE kr.ID_KONKURSA IS NULL;
/

UPDATE KONACNARANGLISTA kr
SET kr.ID_KONKURSA = (
  SELECT MIN(ks.ID_KONKURSA)
  FROM KONKURSSTAVKA ks
  JOIN KONKURSZAMASTERSTUDIJE k ON k.ID_KONKURSA = ks.ID_KONKURSA
  WHERE ks.ID_PROGRAMA = kr.ID_PROGRAMA
    AND k.SKOLSKA_GODINA = kr.SKOLSKA_GODINA
)
WHERE kr.ID_KONKURSA IS NULL;
/

DECLARE
  constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO constraint_count
  FROM user_constraints
  WHERE table_name = 'KONACNARANGLISTA'
    AND constraint_name = 'FK_RANG_LISTA_KONKURS';

  IF constraint_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE KONACNARANGLISTA
      ADD CONSTRAINT FK_RANG_LISTA_KONKURS
      FOREIGN KEY (ID_KONKURSA)
      REFERENCES KONKURSZAMASTERSTUDIJE (ID_KONKURSA)
    ]';
  END IF;
END;
/

DECLARE
  constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO constraint_count
  FROM user_constraints
  WHERE table_name = 'KONACNARANGLISTA'
    AND constraint_name = 'UQ_KON_RANG_LISTA_PROGRAM_GOD';

  IF constraint_count > 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE KONACNARANGLISTA
      DROP CONSTRAINT UQ_KON_RANG_LISTA_PROGRAM_GOD
    ]';
  END IF;
END;
/

DECLARE
  constraint_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO constraint_count
  FROM user_constraints
  WHERE table_name = 'KONACNARANGLISTA'
    AND constraint_name = 'UQ_KON_RANG_LISTA_KON_PROG';

  IF constraint_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      ALTER TABLE KONACNARANGLISTA
      ADD CONSTRAINT UQ_KON_RANG_LISTA_KON_PROG
      UNIQUE (ID_KONKURSA, ID_PROGRAMA)
    ]';
  END IF;
END;
/

DECLARE
  index_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
  INTO index_count
  FROM user_indexes
  WHERE table_name = 'KONACNARANGLISTA'
    AND index_name = 'IDX_KON_RANG_LISTA_KONKURS';

  IF index_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE INDEX IDX_KON_RANG_LISTA_KONKURS
      ON KONACNARANGLISTA (ID_KONKURSA)
    ]';
  END IF;
END;
/

COMMENT ON COLUMN KONACNARANGLISTA.ID_KONKURSA IS 'Konkurs kojem rang lista pripada';
